version: '3.7' # add version number for docker-compose file
services: 
  db: # define container under service ## db - container name for postgres id db
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - myapp_network
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:  #second container is the rails 
    build: ./ 
    user: '501:20'
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres: # named volume


# It defines two services: db for PostgreSQL and rails for your Rails application